# Generated by Django 4.1.5 on 2023-01-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attack', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField()),
                ('attacks', models.ManyToManyField(to='attack.attack')),
                ('poke_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type')),
            ],
        ),
    ]
